### ISSUE TITLE
ZetaIpc 1.0.4.12 - Client does not honor timeout setting

### ISSUE THREAD

**Issue by dataweasel** [UweKeim/ZetaIpc#17]
I am using ZetaIpc between a desktop application (.Net 5) and a Windows Server (.Net 5) on the same machine.  The desktop client is the "IPC Server" and the Windows Service is the "IPC Client".  The idea is when a new message comes into the service, it notifies the desktop app that a new message has arrived.

The service receives messages async. and calls a Received Message Handler when a new message comes in.  I write the message to a database, then kick off a client SEND to let the desktop application know a message has arrived.

If both the desktop app and service are running everything is fine.  If I stop the Desktop application, the service seems to stop at the call to sending a new message notification -- even with a timeout of 100 ms. set.

```
applog.Debug($"BEFORE NEW MSG NOTIFY-{_msg.messageUniqueID}");
SendNewMessageNotification($"{_msg.messageUniqueID};{_msg.messageBody}");
applog.Debug($"AFTER NEW MSG NOTIFY-{_msg.messageUniqueID}");
```

I have this code in the location here I call out to send the message notification.  It logs before and after...and you can see this is the actual file.

![2022-01-14 15_06_22-CollectorService log (516 3 KB) - BareTail](https://user-images.githubusercontent.com/6961443/149587321-a2858be3-073b-4836-b0a4-996e0fcac31a.png)

You can see that when I close the desktop app, we never return from the SendNewMessageNotification method.

Here's the code where I instance the client:

```
//- Configure New Message Notification Client
_ipcClient = new IpcClient();
_ipcClient.Initialize(56455, 100);
```

...and here the code where I send the notification:

```
private void SendNewMessageNotification(string NewMessageData)
{
      _ipcClient.Send(NewMessageData);
      applog.Debug($"Send new message notification: {NewMessageData}");
}
```

-Joe

**Comment by UweKeim** [comment]
I've tried this as you described.

1. Having a running server and a running client.
2. They exchange messages successfully in a loop, one message per second.
3. As soon as I close the server, the client gets an exception that the server denied the connection (i.e. is not there anymore, so no one listens to the port anymore).

So in _my_ test scenario, everything seems to work as expected.

Did I misunderstand you issue report here? And/or can you create a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) for me, please?

**Comment by dataweasel** [comment]
D'oh...

You response reminded me that I needed to wrap a try...catch around the client send.  When I did so...it appears to be working now.  I'll do some more testing and make sure it is as I would expect.  A quick test looks good for the moment.

Thanks for jogging my memory.

-Joe
