### ISSUE TITLE
How to get the client process name in the server when the server receives the request from the client?

### ISSUE THREAD

**Issue by SaiBalaji202** [UweKeim/ZetaIpc#5]
How to get the client process name in the server when the server receives the request from the client? Please help me to achieve this?

**Comment by UweKeim** [comment]
[See here](https://github.com/UweKeim/ZetaIpc#how-to-tell-the-port-from-the-client-to-the-server) for an example.

**Comment by UweKeim** [comment]
Why would you want to do this? Sounds like an [XY problem](http://xyproblem.info) to me.

If you really need it, use the actual IPC of this library to let the client tell the server its name:

1. Call [`Process.GetCurrentProcess()`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.getcurrentprocess) on the client to get the current client process.
1. Call [`Process.ProcessName`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processname?view=netframework-4.7.2) on the returned `Process` object.
1. Pass this name via ZetaIpc to the server.

**Comment by SaiBalaji202** [comment]
I want to let the server know about the client.  I don't want the client to
send this extra information.  So, is there any way for the server to
identify its client's process id?

**Comment by UweKeim** [comment]
The client is sending HTTP requests to the server. In my opinion you cannot determine the process ID of the originator of an HTTP request.

So for me, the answer is **no**, unfortunately.

**Comment by SaiBalaji202** [comment]
Can we get any details about the client from the server?
