### ISSUE TITLE
For which .NET version is this?

### ISSUE THREAD

**Issue by Bluscream** [UweKeim/ZetaIpc#8]
When I try to install it in Visual Studio I get

Error		Could not install package 'ZetaIpc 1.0.0.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by maksim789456** [comment]
3.5 Framework? Are you serious?

**Comment by Bluscream** [comment]
Whats wrong? 3.5 is still being used a lot...

**Comment by Bluscream** [comment]
Why not simply answer the question like "this is only for 4.5 and above"?

**Comment by maksim789456** [comment]
Sorry, really a library for 4.5 and higher
Even I would say for 4.7 in connection with the update under .net standard 2.0

**Comment by Bluscream** [comment]
Thanks

**Comment by UweKeim** [comment]
.NET Framework 4.5.2 is the lowest version still officially supported by Microsoft.

**Comment by Bluscream** [comment]
Does not change the fact that there is still software using it and libraries that work on that framework
